# Site settings
title: merrylin
email: somename@somedomain.com
description: "Just Another Jekyll Theme"
logo_location: "http://bpic.588ku.com/element_pic/00/16/07/20578f8f6784b6a.jpg"

#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge

#Other Global Configuration
exclude: ['README.md']

excerpt_separator: <!--more-->

#show the jumbotron header on index page
show_blog_header: true
