# Site settings
title: merrylin
email: somename@somedomain.com
description: "Just 薄凉 无趣之人"
logo_location: "https://github.com/merrylin77/blog.io/blob/master/_image/view_Fotor.png"

#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge

#Other Global Configuration
exclude: ['README.md']

excerpt_separator: <!--more-->

#show the jumbotron header on index page
show_blog_header: true
